### ISSUE TITLE
请问这个该怎么解决，纯小白

### ISSUE THREAD

**Issue by 3206662637** [Drinkhuahuaniu/INShuaKe#9]
![image](https://github.com/user-attachments/assets/08962a81-4edf-4af1-9962-0dd1b1e52034)
请问这样的该怎么解决

**Comment by Drinkhuahuaniu** [comment]
> ![image](https://private-user-images.githubusercontent.com/121090644/352948423-08962a81-4edf-4af1-9962-0dd1b1e52034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzc5NDUsIm5iZiI6MTcyMjIzNzY0NSwicGF0aCI6Ii8xMjEwOTA2NDQvMzUyOTQ4NDIzLTA4OTYyYTgxLTRlZGYtNGFmMS05OTYyLTBkZDFiMWU1MjAzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwNzIwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTAyZjc5MTUyODc0ZDQyMDJjMjQ0YTk1MWFjMGE0MmMyM2EyYjFkODFkYTM4YzQ1ZWIwYWFlNjAzZmViMGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4pjUQQUGhcS_pP2i3c8Nx-Q7RPO_QUX_fhldjZpIZyw) 请问这样的该怎么解决

y是yes，n是no，输入y敲个回车代表同意

**Comment by 3206662637** [comment]
好的，谢谢。环境配置部分已经完成了，我放到pycharm运行的时候报错如下：
C:\Users\32066\Downloads\INShuaKe-main\.venv\Scripts\python.exe C:\Users\32066\Downloads\INShuaKe-main\main.py 
Traceback (most recent call last):
  File "C:\Users\32066\Downloads\INShuaKe-main\main.py", line 10, in <module>
    asyncio.run(main())
  File "E:\python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "E:\python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\32066\Downloads\INShuaKe-main\main.py", line 7, in main
    await shuake.start()  # 运行 shuake.start() 方法
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\32066\Downloads\INShuaKe-main\Shuake.py", line 19, in start
    self.context = await self.browser.new_context()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\32066\Downloads\INShuaKe-main\.venv\Lib\site-packages\playwright\async_api\_generated.py", line 13328, in new_context
    await self._impl_obj.new_context(
  File "C:\Users\32066\Downloads\INShuaKe-main\.venv\Lib\site-packages\playwright\_impl\_browser.py", line 127, in new_context
    channel = await self._channel.send("newContext", params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\32066\Downloads\INShuaKe-main\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\32066\Downloads\INShuaKe-main\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 509, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\32066\Downloads\INShuaKe-main\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed

进程已结束，退出代码为 1

**Comment by Drinkhuahuaniu** [comment]
> 好的，谢谢。环境配置部分已经完成了，我放到pycharm运行的时候报错如下： C:\Users\32066\Downloads\INShuaKe-main.venv\Scripts\python.exe C:\Users\32066\Downloads\INShuaKe-main\main.py Traceback (most recent call last): File "C:\Users\32066\Downloads\INShuaKe-main\main.py", line 10, in asyncio.run(main()) File "E:\python\Lib\asyncio\runners.py", line 194, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "E:\python\Lib\asyncio\runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\python\Lib\asyncio\base_events.py", line 687, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "C:\Users\32066\Downloads\INShuaKe-main\main.py", line 7, in main await shuake.start() # 运行 shuake.start() 方法 ^^^^^^^^^^^^^^^^^^^^ File "C:\Users\32066\Downloads\INShuaKe-main\Shuake.py", line 19, in start self.context = await self.browser.new_context() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\32066\Downloads\INShuaKe-main.venv\Lib\site-packages\playwright\async_api_generated.py", line 13328, in new_context await self._impl_obj.new_context( File "C:\Users\32066\Downloads\INShuaKe-main.venv\Lib\site-packages\playwright_impl_browser.py", line 127, in new_context channel = await self._channel.send("newContext", params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\32066\Downloads\INShuaKe-main.venv\Lib\site-packages\playwright_impl_connection.py", line 59, in send return await self._connection.wrap_api_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\32066\Downloads\INShuaKe-main.venv\Lib\site-packages\playwright_impl_connection.py", line 509, in wrap_api_call return await cb() ^^^^^^^^^^ File "C:\Users\32066\Downloads\INShuaKe-main.venv\Lib\site-packages\playwright_impl_connection.py", line 97, in inner_send result = next(iter(done)).result() ^^^^^^^^^^^^^^^^^^^^^^^^^ playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
> 
> 进程已结束，退出代码为 1

你config.py里的文件配置了吗？
